version: "3.6"
services:
  frontend:
    container_name: frontend
    build: frontend/.
    restart: always
    ports:
      - 3000:3000
    networks:
      - web
  backend:
    container_name: backend
    build: backend/.
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
    networks:
      - web
  mysql:
    container_name: mysql
    image: mysql:5.7.36
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_SCHEMA}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - web
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
networks:
  web:
